### ISSUE TITLE
possible to support uuid 1 - 4/5?

### ISSUE THREAD

**Issue by lopugit** [VitorLuizC/vue-uuid#1]
/** Feature Request */

Might it be possible to support different versions of uuid?

Like https://www.npmjs.com/package/uuid does?

Thanks so much for this package either way <3

**Comment by lopugit** [comment]
AHAHAHAHAHAHA YOU ALREADY WROTE IT IN YOU MOTHER FUCKER, LEGEND

**Comment by VitorLuizC** [comment]
Since it only exposes deprecated uuid API, it already has support to v1/v4, but not v5.

```
this.$uuid.v1()
this.$uuid.v4()
```

**Comment by VitorLuizC** [comment]
Support to uuid/v5 was added at version 1.0.
