### ISSUE TITLE
Vue 3 compatibility

### ISSUE THREAD

**Issue by mihaileu** [VitorLuizC/vue-uuid#12]
Is there any pan to make this component available for vue 3 ?

**Comment by SlyDave** [comment]
A change of dep requirement is not the only change that is needed to make this vue3 compat.

This package produces the following warning:
[Vue warn]: (deprecation GLOBAL_PROTOTYPE) Vue.prototype is no longer available in Vue 3. Use app.config.globalProperties instead.

**Comment by romain130492** [comment]
any news?

**Comment by MartinX3** [comment]
Use https://github.com/uuidjs/uuid

**Comment by VitorLuizC** [comment]
I have been working with ReactJS and other tools for the last few years, so I'm sorry for not been actively maintaining this package. In the next few days, I'll make a new release to support Vue 3.

**Comment by VitorLuizC** [comment]
https://github.com/VitorLuizC/vue-uuid/releases/tag/v3.0.0
