### ISSUE TITLE
Got error "Uncaught TypeError: Cannot set properties of undefined (setting '$uuid')" while trying to use package in nuxt

### ISSUE THREAD

**Issue by Ayoazeez26** [VitorLuizC/vue-uuid#18]
I have the package installed and created a custom plugin file for it and added it to my plugins array in the nuxt.config.js file. After importing it into the component I intend to use it on I am getting an error.
![Screenshot from 2022-02-12 03-54-28](https://user-images.githubusercontent.com/44169294/153694009-2ca3abba-4f7e-41ea-a39d-218ac62e0a0d.png)
Hovering over the underlined part reveals "Uncaught TypeError: Cannot set properties of undefined (setting '$uuid')"

**Comment by robertkabat** [comment]
Did you manage to solve that issue?
