### ISSUE TITLE
v5() not working without additional params?

### ISSUE THREAD

**Issue by turnitonagain** [VitorLuizC/vue-uuid#5]
Using the testcode, I can get v1() and v4() to work, but v5() raises two errors:

- value must be an array of bytes
then:

- namespace must be uuid string or an Array of 16 byte values

If I pass two parameters as above, it works. Is this something I'm doing wrong, or does the test.js code need the params added?

**Comment by VitorLuizC** [comment]
You're right. My README's example is wrong

**Comment by VitorLuizC** [comment]
Now its fixed.
