### ISSUE TITLE
Types definition

### ISSUE THREAD

**Issue by zbianca** [VitorLuizC/vue-uuid#8]
Hi, Vitor!

I ran into problems with this package while using the latest types definition for uuid from DefinitelyTyped. 

You can find more details here:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42634#issuecomment-637818676

**Comment by VitorLuizC** [comment]
Hi, @zbianca
Seems like the uuid version I'm using is too old, I'll upgrade it and its types to the recent stable version.

**Comment by VitorLuizC** [comment]
Fixed and published with some upgrades under 2.0.2 version.

```sh
npm i vue-uuid@^2.0.2
```

**Comment by zbianca** [comment]
Great! Thank you!
